# Generated by Django 4.0.4 on 2022-05-24 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nonogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=9)),
                ('combos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=9), size=None)),
            ],
        ),
    ]
